### PR TITLE
Update admin.svg - too large icon.

### PR DESCRIPTION
**Pull request by sysoftlab**
Sorry. I can not speak English very well. I rely on Google Translate.
There was a symptom of an icon appearing large on the screen because you did not specify the size in admin.svg.
Fix it.

### CODE REVIEW

**Comment by sysoftlab** [comment]
/lib/plugins/searchindex/admin.svg

**Comment by gerardnico** [comment]
Ah ah, i just see that you made a pull request as well. You can ping the issue by adding a hastag # and the number of the issue as that. #44

**Comment by splitbrain** [comment]
The size of admin icons should be set by the template. I recommend opening a bug report for the template you use.

**Comment by gerardnico** [comment]
Ok .. i'm a little bit lost on the workflow.

Width and height are the default value of the svg. No ?

Actually all svg icon have a 24x24 by default (sqlite, wiki upgrade, ...)

I don't see why we should still have a css rule and gives the burden to the template.

Example:
https://github.com/splitbrain/dokuwiki-plugin-upgrade/blob/master/admin.svg?short_path=35c9774

**Comment by gerardnico** [comment]
It had no cost at all to accept the PR, I'm a little bit lost. Hope you are all good.

**Comment by gerardnico** [comment]
From the 15 svg that I got, this is the only one.

image

**Pull request closed without merging**
